### ISSUE TITLE
Edge is broken

### ISSUE THREAD

**Issue by lgreif** [A-Team-Rowan-University/a-team-website#75]
The issue is that sign in the dropdown isn't a thing

**Comment by timothyhollabaugh** [comment]
https://github.com/jgthms/bulma/issues/2503

**Comment by JOHNeMac36** [comment]
I think this issue is was fixed, Edge users were able to submit tests last night and the navbar is now an dropdown

**Comment by timothyhollabaugh** [comment]
Edge users still don't get the drop down. The ones that worked are where
Google automatically signed them in
